spring:
  profiles:
    active: 
    - dev
---
spring:
  profiles: dev   # 开发环境
  application:
    name: microservicecloud-config-liukai-dev
---
spring:
  profiles: test    # 测试环境
  application:
    name: microservicecloud-config-liukai-test

# 需要保存为utf-8格式